"""
PR Agent Service — optimised for speed.

Key improvements over v1:
- Batch-fetch all AI fixes in ONE query instead of N queries (one per vuln)
- Deduplicate files so each file is fetched from GitHub only ONCE
- Concurrent GitHub file fetches via asyncio.gather
- Cap actionable fixes at MAX_FILES_PER_PR to avoid GitHub API rate limits
- PR body truncated to MAX_PR_BODY_CHARS to avoid GitHub 65536-char limit
"""
import asyncio
import logging
import re
from datetime import datetime, timezone
from typing import Optional

from github import Github, GithubException
from github.InputGitTreeElement import InputGitTreeElement

from app.core.config import settings
from app.core.db import db

logger = logging.getLogger(__name__)

# Safety caps
MAX_FILES_PER_PR  = 20   # GitHub tree API slows above this
MAX_PR_BODY_CHARS = 60_000


# ── Helpers ───────────────────────────────────────────────────────────────────

def _parse_owner_repo(repo_url: str) -> tuple[str, str]:
    match = re.search(r"github\.com[/:]([^/]+)/([^/.\s]+?)(?:\.git)?$", repo_url)
    if not match:
        raise ValueError(f"Cannot parse GitHub URL: {repo_url}")
    return match.group(1), match.group(2)


def _severity_emoji(severity: str) -> str:
    return {"critical": "🔴", "high": "🟠", "medium": "🟡", "low": "🟢"}.get(
        severity.lower(), "⚪"
    )


def _build_pr_body(vulnerabilities: list[dict], fix_map: dict[str, dict]) -> str:
    critical = sum(1 for v in vulnerabilities if v.get("severity") == "critical")
    high     = sum(1 for v in vulnerabilities if v.get("severity") == "high")
    medium   = sum(1 for v in vulnerabilities if v.get("severity") == "medium")
    low      = sum(1 for v in vulnerabilities if v.get("severity") == "low")

    lines = [
        "## 🔒 SecureShift Automated Security Fixes",
        "",
        "> Auto-generated by **SecureShift AI Security Scanner**. Review before merging.",
        "",
        "### 📊 Summary",
        "",
        "| Severity | Count |",
        "|----------|-------|",
        f"| 🔴 Critical | {critical} |",
        f"| 🟠 High     | {high}     |",
        f"| 🟡 Medium   | {medium}   |",
        f"| 🟢 Low      | {low}      |",
        f"| **Total**   | **{len(vulnerabilities)}** |",
        "",
        "---",
        "### 🛠️ Fixes Applied",
        "",
    ]

    for i, vuln in enumerate(vulnerabilities[:50], 1):   # cap at 50 entries in body
        fix  = fix_map.get(vuln["id"])
        emoji = _severity_emoji(vuln.get("severity", ""))
        lines += [
            f"#### {i}. {emoji} `{vuln.get('vulnerability_type','Unknown')}` — "
            f"`{vuln.get('file_path','unknown')}`",
            f"- **Severity:** {vuln.get('severity','unknown').upper()}",
            f"- **Line:** {vuln.get('line_number') or 'N/A'}",
            f"- **Description:** {vuln.get('description','')}",
        ]
        if fix and fix.get("fixed_code"):
            lines += [
                f"- **AI Fix** *(confidence: {int((fix.get('confidence_score') or 0.5)*100)}%)*",
                "```python",
                fix["fixed_code"].strip()[:500],   # truncate huge snippets
                "```",
            ]
        lines.append("")

    if len(vulnerabilities) > 50:
        lines.append(f"*…and {len(vulnerabilities)-50} more vulnerabilities not shown.*\n")

    lines += [
        "---",
        "⚠️ AI-generated fixes may require manual review.",
        f"*Generated {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')} by SecureShift*",
    ]

    body = "\n".join(lines)
    if len(body) > MAX_PR_BODY_CHARS:
        body = body[:MAX_PR_BODY_CHARS] + "\n\n*[body truncated]*"
    return body


# ── Main service ──────────────────────────────────────────────────────────────

class PRAgent:

    def __init__(self, github_token: Optional[str] = None):
        token = github_token or settings.GITHUB_TOKEN
        if not token:
            raise ValueError("GITHUB_TOKEN is not configured")
        self._gh    = Github(token)
        self._token = token

    async def create_pr_for_scan(
        self,
        scan_id: str,
        repo_url: str,
        base_branch: str = "main",
        github_token: Optional[str] = None,
    ) -> dict:
        token = github_token or self._token
        gh    = Github(token) if github_token else self._gh

        # ── 1. Batch-fetch vulnerabilities ────────────────────────────────────
        vulnerabilities = db.get_vulnerabilities(scan_id)
        if not vulnerabilities:
            raise ValueError(f"No vulnerabilities found for scan {scan_id}")

        vuln_ids = [v["id"] for v in vulnerabilities]

        # ── 2. Batch-fetch ALL fixes in ONE query ─────────────────────────────
        try:
            fixes_res = (
                db.client.table("ai_fixes")
                .select("*")
                .in_("vulnerability_id", vuln_ids)
                .or_("is_applied.is.null,is_applied.eq.false")
                .execute()
            )
            all_fixes: list[dict] = fixes_res.data or []
        except Exception as e:
            logger.warning(f"Batch fix fetch failed, falling back: {e}")
            all_fixes = []
            for vid in vuln_ids:
                all_fixes.extend(db.get_ai_fixes(vid))

        fix_map: dict[str, dict] = {}
        for f in all_fixes:
            vid = f.get("vulnerability_id")
            # Accept fix if it has fixed_code (even a placeholder) or suggested_fix
            has_code = bool(f.get("fixed_code") and str(f["fixed_code"]).strip())
            if vid and (has_code or f.get("suggested_fix")) and vid not in fix_map:
                fix_map[vid] = f

        # ── 3. Build vuln→fix pairs, deduplicate files ────────────────────────
        vuln_map = {v["id"]: v for v in vulnerabilities}

        # file_path → list of (vuln, fix) — only one fix per unique file
        file_patches: dict[str, tuple[dict, dict]] = {}
        for vid, fix in fix_map.items():
            vuln = vuln_map.get(vid)
            if not vuln:
                continue
            fp = vuln.get("file_path", "").lstrip("/")
            if not fp:
                continue
            if fp not in file_patches:          # first fix wins per file
                file_patches[fp] = (vuln, fix)

        # Cap to avoid GitHub rate limits
        if len(file_patches) > MAX_FILES_PER_PR:
            logger.warning(f"Capping fixes from {len(file_patches)} → {MAX_FILES_PER_PR} files")
            file_patches = dict(list(file_patches.items())[:MAX_FILES_PER_PR])

        if not file_patches:
            raise ValueError(
                "No actionable fixes found. Run a scan first and ensure AI fixes "
                "contain fixed_code."
            )

        # ── 4. Resolve GitHub repo ────────────────────────────────────────────
        owner, repo_name = _parse_owner_repo(repo_url)
        try:
            gh_repo = gh.get_repo(f"{owner}/{repo_name}")
        except GithubException as e:
            raise ValueError(f"Cannot access repo '{owner}/{repo_name}': {e.data}")

        try:
            base_ref = gh_repo.get_branch(base_branch)
        except GithubException:
            base_branch = gh_repo.default_branch
            base_ref    = gh_repo.get_branch(base_branch)

        base_sha = base_ref.commit.sha

        # ── 5. Fetch all files concurrently ───────────────────────────────────
        async def fetch_file(fp: str) -> tuple[str, Optional[str]]:
            """Return (file_path, content_or_None)."""
            try:
                loop = asyncio.get_event_loop()
                contents = await loop.run_in_executor(
                    None, lambda: gh_repo.get_contents(fp, ref=base_branch)
                )
                return fp, contents.decoded_content.decode("utf-8")
            except Exception as exc:
                logger.warning(f"Could not fetch {fp}: {exc}")
                return fp, None

        file_contents: dict[str, str] = {}
        results = await asyncio.gather(*[fetch_file(fp) for fp in file_patches])
        for fp, content in results:
            if content is not None:
                file_contents[fp] = content

        # ── 6. Apply patches ──────────────────────────────────────────────────
        tree_elements: list[InputGitTreeElement] = []
        files_changed: list[str] = []
        applied_fix_ids: list[str] = []

        for fp, (vuln, fix) in file_patches.items():
            current = file_contents.get(fp)
            if current is None:
                continue

            patched = self._apply_patch(
                current,
                vuln.get("code_snippet"),
                fix["fixed_code"],
                vuln.get("line_number"),
            )
            if patched == current:
                logger.info(f"No change for {fp}, skipping")
                continue

            tree_elements.append(
                InputGitTreeElement(path=fp, mode="100644", type="blob", content=patched)
            )
            files_changed.append(fp)
            applied_fix_ids.append(fix["id"])

        if not tree_elements:
            raise ValueError(
                "Patches produced no changes. The AI fix snippets may not match "
                "the current file content."
            )

        # ── 7. Batch commit via Tree API ──────────────────────────────────────
        ts         = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
        new_branch = f"fix/security-patches-{ts}"

        base_tree  = gh_repo.get_git_tree(base_sha)
        new_tree   = gh_repo.create_git_tree(tree_elements, base_tree)

        parent_commit = gh_repo.get_git_commit(base_sha)
        new_commit    = gh_repo.create_git_commit(
            message=(
                f"fix: SecureShift auto security patches\n\n"
                f"{len(tree_elements)} file(s) patched — Scan {scan_id}"
            ),
            tree=new_tree,
            parents=[parent_commit],
        )
        gh_repo.create_git_ref(ref=f"refs/heads/{new_branch}", sha=new_commit.sha)
        logger.info(f"Pushed branch '{new_branch}' ({len(tree_elements)} files)")

        # ── 8. Open Draft PR ──────────────────────────────────────────────────
        pr = gh_repo.create_pull(
            title="🔒 SecureShift Automated Security Fixes",
            body=_build_pr_body(vulnerabilities, fix_map),
            head=new_branch,
            base=base_branch,
            draft=True,
        )
        logger.info(f"Draft PR: {pr.html_url}")

        # ── 9. Persist results (batch) ────────────────────────────────────────
        db.client.table("scans").update({"pr_url": pr.html_url}).eq("id", scan_id).execute()

        if applied_fix_ids:
            now = datetime.now(timezone.utc).isoformat()
            db.client.table("ai_fixes").update({
                "is_applied": True,
                "applied_at": now,
            }).in_("id", applied_fix_ids).execute()

        return {
            "pr_url":               pr.html_url,
            "pr_number":            pr.number,
            "branch":               new_branch,
            "base_branch":          base_branch,
            "files_changed":        files_changed,
            "fixes_applied":        len(tree_elements),
            "total_vulnerabilities": len(vulnerabilities),
        }

    # ── Patch helper ──────────────────────────────────────────────────────────

    @staticmethod
    def _apply_patch(
        source: str,
        snippet: Optional[str],
        fixed_code: str,
        line_number: Optional[int],
    ) -> str:
        if snippet and snippet.strip() in source:
            return source.replace(snippet.strip(), fixed_code.strip(), 1)
        if line_number and line_number > 0:
            lines = source.splitlines(keepends=True)
            idx = line_number - 1
            if 0 <= idx < len(lines):
                lines[idx] = fixed_code.strip() + "\n"
                return "".join(lines)
        return source


def get_pr_agent(token: str | None = None) -> PRAgent:
    return PRAgent(github_token=token)
